#!/bin/bash

FILE=draft-young-md-query.xml
TAG=$(grep docName ${FILE} | sed "s/.*docName=\"//" | sed "s/\".*//")
git tag -s ${TAG} -m "Tag ${TAG}"
git push origin ${TAG}

FILE=draft-young-md-query-saml.xml
TAG=$(grep docName ${FILE} | sed "s/.*docName=\"//" | sed "s/\".*//")
git tag -s ${TAG} -m "Tag ${TAG}"
git push origin ${TAG}
